apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: overmind
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/Black-And-White-Club/resume-infrastructure.git
        revision: main
        files:
          - path: "argocd-applications/*"
  template:
    metadata:
      name: '{{ trimSuffix ".yaml" .path.filename }}'
      labels:
        type: applicationset-definition
    spec:
      project: resume-portfolio
      source:
        repoURL: https://github.com/Black-And-White-Club/resume-infrastructure.git
        targetRevision: main
        path: "{{ .path.path }}"
        directory:
          include: "{{ .path.filename }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
