prometheus:
  prometheusSpec:
    podMonitorNamespaceSelector:
      matchExpressions: []
    podMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false

    ruleNamespaceSelector:
      matchExpressions: []
    ruleSelector: {}
    ruleSelectorNilUsesHelmValues: false

    serviceMonitorNamespaceSelector:
      matchExpressions: []
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
