serviceMonitors:
  resume-backend:
    enabled: true
    namespace: resume-app
    selector:
      matchLabels:
        app: resume-backend
    namespaceSelector:
      matchNames:
        - resume-app
    endpoints:
      - port: https
        path: /metrics
        interval: 2m

  ingress-nginx:
    enabled: true
    namespace: resume-app
    selector:
      matchLabels:
        app.kubernetes.io/name: ingress-nginx
    endpoints:
      - port: metrics
        interval: 2m

  argocd:
    enabled: true
    namespace: argocd
    selector:
      matchLabels:
        app.kubernetes.io/name: argocd
    endpoints:
      - port: metrics
        interval: 2m
