# Minimal NATS with JetStream for frolf-bot
nats:
  image: nats:2.11.1
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

config:
  jetstream:
    enabled: true
  cluster:
    enabled: false

persistence:
  enabled: true
  size: 2Gi
  storageClassName: "local-path"

service:
  type: ClusterIP
  ports:
    - name: nats
      port: 4222
      targetPort: 4222
