apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resume-backend.yaml
  - resume-frontend.yaml

replacements:
  - source:
      kind: Secret
      name: project-id
      namespace: resume-app
      fieldPath: data.GCP_PROJECT_ID
    targets:
      - select:
          kind: Deployment
          name: resume-frontend
        fieldPaths:
          - spec.template.spec.containers.0.image
      - select:
          kind: Deployment
          name: resume-backend
        fieldPaths:
          - spec.template.spec.containers.0.image

images:
  - name: us-central1-docker.pkg.dev/*/portfolio-app-images-charts/resume-frontend
    newName: us-central1-docker.pkg.dev/$(REPLACE_PROJECT_ID)/portfolio-app-images-charts/resume-frontend
  - name: us-central1-docker.pkg.dev/*/portfolio-app-images-charts/resume-backend
    newName: us-central1-docker.pkg.dev/$(REPLACE_PROJECT_ID)/portfolio-app-images-charts/resume-backend

namePrefix: resume-portfolio-project-
