apiVersion: v1
kind: Service
metadata:
  name: resume-frontend-svc
  namespace: resume-app
  labels:
    job: astro-web
    app: resume-frontend
    tier: frontend
spec:
  selector:
    app: resume-frontend
  ports:
    - name: web-port
      port: 80
      targetPort: 3000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-frontend
  namespace: resume-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-frontend
  template:
    metadata:
      labels:
        app: resume-frontend
    spec:
      imagePullSecrets:
        - name: gcp-credentials
      containers:
        - name: resume-frontend
          # image: resume-frontend:b6638c4
          image: us-central1-docker.pkg.dev/resume-portfolio-project/portfolio-app-images-charts/resume-frontend:b6638c4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
