# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
prometheus:
  prometheusSpec:
    podMonitorNamespaceSelector:
      matchExpressions: []
    podMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false

    ruleNamespaceSelector:
      matchExpressions: []
    ruleSelector: {}
    ruleSelectorNilUsesHelmValues: false

    serviceMonitorNamespaceSelector:
      matchExpressions: []
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
