# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
prometheus:
  prometheusSpec:
    podMonitorNamespaceSelector:
      matchExpressions: []
    podMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false

    ruleNamespaceSelector:
      matchExpressions: []
    ruleSelector: {}
    ruleSelectorNilUsesHelmValues: false

    serviceMonitorNamespaceSelector:
      matchExpressions: []
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
grafana:
  grafana.ini:
    auth.anonymous:
      enabled: true
      device_limit: 10
      org_role: Viewer
    security:
      allow_embedding: true
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/secure-backends: "true"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-origin: "http://jaromero.cloud"
    hosts:
      - grafana.jaromero.cloud
