apiVersion: v1
kind: Service
metadata:
  name: resume-backend-svc
  namespace: resume-app
  labels:
    job: go-api
    app: resume-backend
spec:
  selector:
    app: resume-backend
  ports:
    - name: api-port
      protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-backend
  namespace: resume-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=iad.ocir.io/id2uwn5pyixh/resume/backend
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^[0-9a-f]{7}$
    argocd-image-updater.argoproj.io/backend.pull-secret: pullsecret:resume-app/ocir-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-backend
  template:
    metadata:
      labels:
        app: resume-backend
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: resume-backend
          image: iad.ocir.io/id2uwn5pyixh/resume/backend:a5cb7d5
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: backend-db-credentials
          env:
            - name: ALLOWED_ORIGINS
              value: https://jaromero.cloud/
            - name: APP_ENV
              value: dev
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 1

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: resume-backend-monitor
  namespace: resume-app
  labels:
    app: resume-backend-monitor
    release: prometheus
spec:
  jobLabel: job
  selector:
    matchLabels:
      app: resume-backend
  endpoints:
    - port: api-port
      path: /metrics
      interval: 3m
