apiVersion: v1
kind: Service
metadata:
  name: resume-frontend-svc
  namespace: resume-app
  labels:
    job: astro-web
    app: resume-frontend
    tier: frontend
spec:
  selector:
    app: resume-frontend
  ports:
    - name: web-port
      port: 443
      targetPort: 3000
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-frontend
  namespace: resume-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: frontend=iad.ocir.io/id2uwn5pyixh/resume/frontend
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^[0-9a-f]{7}$
    argocd-image-updater.argoproj.io/frontend.pull-secret: pullsecret:resume-app/ocir-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-frontend
  template:
    metadata:
      labels:
        app: resume-frontend
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: resume-frontend
          image: iad.ocir.io/id2uwn5pyixh/resume/frontend:94ab36a
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
