apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
        - name: traefik
          image: traefik:v3.2.0
          args:
            - --providers.kubernetesCRD
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --providers.kubernetesIngress
            - --ping
            - --metrics.prometheus=true
            - --metrics.prometheus.entryPoint=traefik
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: metrics
              containerPort: 8082
          volumeMounts:
            - name: acme-json
              mountPath: /acme.json
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: acme-json
          hostPath:
            path: /var/lib/traefik/acme.json
            type: FileOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: traefik-metrics
  namespace: traefik
spec:
  selector:
    app: traefik
  ports:
    - protocol: TCP
      name: metrics
      port: 8082
      targetPort: metrics
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resume-app-ingress
  namespace: resume-app
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: jaromero.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: resume-frontend-svc
                port:
                  number: 80
          - path: /api/count
            pathType: Prefix
            backend:
              service:
                name: resume-backend-svc
                port:
                  number: 8000
  tls:
    - hosts:
        - jaromero.cloud
      secretName: letsencrypt-prod-tls

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: resume-app-route
  namespace: resume-app
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`jaromero.cloud`)
      kind: Rule
      services:
        - name: resume-frontend-svc
          port: 80
          annotations:
            traefik.io/service.serverstransport.address: 35.208.254.34:80
