apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik-monitor
  namespace: traefik
  labels:
    app: traefik
spec:
  selector:
    matchLabels:
      app: traefik
  namespaceSelector:
    matchNames:
      - traefik
  endpoints:
    - port: metrics
      path: /metrics
      interval: 3m
