ingressClass:
  name: traefik-helm
# Traefik Helm Chart values.yaml

deployment:
  annotations:
    prometheus.io/scrape: "true" # Enable Prometheus scraping
    prometheus.io/port: "9100" # Traefik's metrics port

service:
  type: LoadBalancer

ports:
  web:
    port: 80
    nodePort: 32080 # Assign a fixed NodePort for HTTP
    expose: true
    protocol: TCP
  websecure:
    port: 443
    nodePort: 32443 # Assign a fixed NodePort for HTTPS
    expose: true
    protocol: TCP

entryPoint:
  metrics:
    address: ":9100"

metrics:
  prometheus:
    enabled: true # Enable Prometheus metrics
    entryPoint: metrics # Expose metrics on the secure port

# Configure IngressRoute for your application (alternative to Ingress)
ingressRoute:
  dashboard:
    enabled: true
  enabled: true
  annotations: {} # Add any annotations needed for your IngressRoute

  # Define your routes here (similar to Ingress rules)
  routes:
    - match: Host(`jaromero.cloud`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: resume-frontend-svc
          port: 80
    - match: Host(`jaromero.cloud`) && PathPrefix(`/api/count`)
      kind: Rule
      services:
        - name: resume-backend-svc
          port: 8000
