# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
# Enable Traefik to use Let's Encrypt
# certificatesResolvers:
#   letsEncrypt:
#     acme:
#       email: romero.jace@gmail.com
#       storage: /data/acme.json
#       tlsChallenge: {} # Use TLS challenge

service:
  spec:
    externalTrafficPolicy: Cluster
    loadBalancerIP: "34.49.45.74"

# Persistence for certificates
persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 128Mi
  storageClass: ""
  volumeName: traefik-data
  path: /data
  hostPath:
    path: /var/lib/traefik/acme.json
    type: FileOrCreate

ingressRoute:
  resumeAppIngress:
    metadata:
      name: resume-app-ingress
      namespace: resume-app
    spec:
      entryPoints:
        - websecure
      routes:
        - match: Host(`jaromero.cloud`)
          kind: Rule
          services:
            - name: resume-frontend-svc
              port: 80
        - match: Host(`jaromero.cloud`) && PathPrefix(`/api/count`)
          kind: Rule
          services:
            - name: resume-backend-svc
              port: 8000
      # tls:
      #   certResolver: letsEncrypt

metrics:
  prometheus:
    service:
      enabled: true
    disableAPICheck: false
    serviceMonitor:
      enabled: true
      metricRelabelings:
        - sourceLabels: [__name__]
          separator: ;
          regex: ^fluentd_output_status_buffer_(oldest|newest)_.+
          replacement: $1
          action: drop
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          separator: ;
          regex: ^(.*)$
          targetLabel: nodename
          replacement: $1
          action: replace
      jobLabel: traefik
      interval: 3m
      honorLabels: true
    prometheusRule:
      enabled: true
      rules:
        - alert: TraefikDown
          expr: up{job="traefik"} == 0
          for: 5m
          labels:
            context: traefik
            severity: warning
          annotations:
            summary: "Traefik Down"
            description: "{{ $labels.pod }} on {{ $labels.nodename }} is down"
