apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resume-app-ingress
  namespace: resume-app
spec:
  ingressClassName: traefik-helm
  rules:
    - host: jaromero.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: resume-frontend-svc
                port:
                  number: 80
          - path: /api/count
            pathType: Prefix
            backend:
              service:
                name: resume-backend-svc
                port:
                  number: 8000
