apiVersion: argoproj.io/v1alpha1
kind: Application
project: resume-portfolio
metadata:
  name: prometheus
  namespace: argocd
destination:
  server: https://kubernetes.default.svc
  namespace: prometheus
sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 65.5.0
    helm:
      valueFiles:
        - $values/charts/prometheus/values.yaml
    chart: kube-prometheus-stack
  - repoURL: https://github.com/Black-And-White-Club/resume-infrastructure.git
    path: charts/prometheus
    targetRevision: main
    ref: values
