apiVersion: v1
kind: Service
metadata:
  name: resume-frontend-svc
  namespace: resume-app
  labels:
    job: astro-web
    app: resume-frontend
    tier: frontend
spec:
  selector:
    app: resume-frontend
  ports:
    - name: web-port
      port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: resume-frontend-config
  namespace: resume-app
data:
  API_URL: "https://resume-frontend.test"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-frontend
  namespace: resume-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-frontend
  template:
    metadata:
      labels:
        app: resume-frontend
    spec:
      containers:
        - name: resume-frontend
          image: us-central1-docker.pkg.dev/${GCP_PROJECT_ID}/portfolio-app-images/resume-frontend:039598c
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: resume-frontend-config
                  key: API_URL
