apiVersion: v1
kind: Service
metadata:
  name: resume-backend-svc
  namespace: resume-app
  labels:
    job: go-api
    app: resume-backend
spec:
  selector:
    app: resume-backend
  ports:
    - name: api-port
      protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-backend
  namespace: resume-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-backend
  template:
    metadata:
      labels:
        app: resume-backend
    spec:
      imagePullSecrets:
        - name: gcp-credentials
      containers:
        - name: resume-backend
          # image: resume-backend:3f52a15
          image: alpine # Use a dummy image here
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add docker-cli
              GCP_PROJECT_ID=$(echo $GCP_PROJECT_ID | tr '[:upper:]' '[:lower:]')
              IMAGE_NAME="us-central1-docker.pkg.dev/${GCP_PROJECT_ID}/portfolio-app-images-charts/resume-backend:3f52a15"
              echo "Pulling image: ${IMAGE_NAME}"
              docker pull "${IMAGE_NAME}"
              /main/app
          envFrom:
            - secretRef:
                name: project-id
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: ALLOWED_ORIGINS
              value: jaromero.cloud
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 1

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: resume-backend-monitor
  namespace: resume-app
  labels:
    app: resume-backend-monitor
    release: prometheus
spec:
  jobLabel: job
  selector:
    matchLabels:
      app: resume-backend
  endpoints:
    - port: api-port
      path: /metrics
      interval: 30m
