apiVersion: v1
kind: Service
metadata:
  name: resume-frontend-svc
  namespace: resume-app
  labels:
    job: astro-web
    app: resume-frontend
    tier: frontend
spec:
  selector:
    app: resume-frontend
  ports:
    - name: web-port
      port: 80
      targetPort: 3000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-frontend
  namespace: resume-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-frontend
  template:
    metadata:
      labels:
        app: resume-frontend
    spec:
      initContainers:
        - name: install-and-pull-image
          image: docker:cli
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add curl
              curl -fsSL "https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v2.1.25/docker-credential-gcr_linux_amd64-2.1.25.tar.gz" \
                | tar xz docker-credential-gcr
              chmod +x docker-credential-gcr
              mv docker-credential-gcr /usr/bin/
              docker-credential-gcr configure-docker --registries=us-central1-docker.pkg.dev
              docker pull us-central1-docker.pkg.dev/resume-portfolio-project/portfolio-app-images-charts/resume-frontend:f71ca09
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
      containers:
        - name: resume-frontend
          # localimage: resume-frontend:f71ca09
          image: us-central1-docker.pkg.dev/resume-portfolio-project/portfolio-app-images-charts/resume-frontend:f71ca09
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
