apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resume-app
  namespace: resume-app
spec:
  destination:
    server: https://10.128.0.16:6443
    namespace: resume-app
  project: resume-portfolio
  source:
    repoURL: https://github.com/Black-And-White-Club/resume-infrastructure.git
    targetRevision: main
    path: kubernetes-manifests/base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
