apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-backend
  namespace: resume-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-backend
  template:
    metadata:
      labels:
        app: resume-backend
    spec:
      containers:
        - name: resume-backend
          image: us-central1-docker.pkg.dev/${GCP_PROJECT_ID}/portfolio-app-images/resume-backend:8e889f5
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
