apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: resume-portfolio
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 33.0.0
      helm:
        valueFiles:
          - $values/charts/traefik/values.yaml
    - repoURL: https://github.com/Black-And-White-Club/resume-infrastructure.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
