# Dedicated Postgres for Frolf Bot
auth:
  username: local
  password: local
  postgresPassword: local
  database: frolfbot

primary:
  persistence:
    enabled: true
    storageClass: "local-path"
    size: 5Gi

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

metrics:
  enabled: false
