apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-watcher
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Black-And-White-Club/resume-infrastructure.git 
        revision: main
        directories:
          - path: "argocd-applications/*"
  template:
    metadata:
      name: '{{ name }}'
    spec:
      project: resume-portfolio
      source:
        repoURL: https://github.com/Black-And-White-Club/resume-infrastructure.git
        targetRevision: main 
        path: '{{ path }}' 
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ namespace }}' 
