apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-watcher
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Black-And-White-Club/resume-infrastructure.git 
        revision: main
        files:
          - path: "argocd-applications/*.yaml"
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: resume-portfolio
      source:
        repoURL: https://github.com/Black-And-White-Club/resume-infrastructure.git
        targetRevision: main 
        path: '{{ path.dir }}' 
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ default "default" .namespace }}'
