apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-resources
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Black-And-White-Club/resume-infrastructure.git
        revision: main
        directories:
          - path: cluster-resources
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        type: cluster-resources-management
        open: me-for-more
    spec:
      project: resume-portfolio
      source:
        repoURL: https://github.com/Black-And-White-Club/resume-infrastructure.git
        targetRevision: main
        path: '{{ path }}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
