apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hall-monitor
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/Black-And-White-Club/resume-infrastructure.git
        revision: main
        files:
          - path: "argocd-applications/*-appset.yaml"
          - path: "argocd-applications/hall-monitor.yaml"
  template:
    metadata:
      name: '{{ .path.basename }}'
      labels:
        type: applicationset-definition
    spec:
      project: resume-portfolio
      source:
        repoURL: https://github.com/Black-And-White-Club/resume-infrastructure.git
        targetRevision: main
        path: '{{ .path.path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
