apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: resume-app-components
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Black-And-White-Club/resume-infrastructure.git
        revision: main
        files:
          - path: "resume-app-manifests/*.yaml"
  template:
    metadata:
      name: '{{ path.filename }}'
      labels:
        app: resume-app
        component: '{{ path.basenameNormalized }}'
        type: resume-component
    spec:
      project: resume-portfolio
      source:
        repoURL: https://github.com/Black-And-White-Club/resume-infrastructure.git
        targetRevision: main
        path: '{{ path }}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
