apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resume-app
  namespace: argocd
  labels:
    open: me-for-more
    type: resume-application
spec:
  project: resume-portfolio
  source:
    repoURL: https://github.com/Black-And-White-Club/resume-infrastructure.git
    targetRevision: main
    path: resume-app-manifests
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
