apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-storage
  namespace: resume-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: oci-block-storage
