apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-local-pvc
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: oci-block-storage
