apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-storage
  namespace: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: db-storage
  storageClassName: ""
