applicationSet:
  metrics:
    enabled: true
    path: /metrics
    serviceMonitor:
      enabled: true
      autodetect: false
      interval: 2m
      annotations: {}
      additionalLabels: {}
      namespace: argocd

controller:
  metrics:
    enabled: true
    path: /metrics
    serviceMonitor:
      enabled: true
      autodetect: false
      interval: 2m
      annotations: {}
      additionalLabels: {}
      namespace: argocd

server:
  metrics:
    enabled: true
    path: /metrics
    serviceMonitor:
      enabled: true
      autodetect: false
      interval: 2m
      annotations: {}
      additionalLabels: {}
      namespace: argocd
