apiVersion: v1
kind: Service
metadata:
  name: resume-backend
  namespace: resume-app
spec:
  selector:
    app: resume-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
