apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gke-ingress
  labels:
    release: prometheus # Match the release label of your Prometheus installation
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx # This label typically identifies the GKE Ingress
  endpoints:
    - port: metrics
      interval: 15s # Adjust the scrape interval as needed
