name: Helm Chart Release

on:
  push:
    branches:
      - main
    paths:
      - "charts/pre-pull-image/**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Release Chart
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts/pre-pull-image

        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
